### ISSUE TITLE
Kivy on_press/on_release fired multiple times

### ISSUE THREAD

**Issue by AndreMiras** [AndreMiras/PyWallet#7]
For some reason the all the Kivy click events get fired multiple times.
Even moving the mouse above a button fires the event.
`Kivy==1.10.0`
Code to reproduce:
`main.py`:
```python
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.config import Config


class Controls(BoxLayout):

    pass


class TouchApp(App):

    def build(self):
        return Controls()


if __name__ == '__main__':
    TouchApp().run()
```

`touch.kv`:
```
#:kivy 1.9.1

<Controls>

    Button:
        text: 'Touch here'
        on_press: print "on_press"
        on_release: print "on_release"
```
